# Dockerfile para Google Cloud Run Job
FROM python:3.13-slim

# Instala dependências do sistema
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.7.13 /uv /uvx /bin/

ADD . /app
WORKDIR /app
RUN uv sync --locked

ENTRYPOINT ["uv", "run", "vendas.py"]